### ISSUE TITLE
Drawing issue with grabber

### ISSUE THREAD

**Issue by DFergFLA** [unarix/haiku_darkstyle#10]
![image](https://user-images.githubusercontent.com/32622501/133868199-a49b83bc-45d8-4928-a951-9f52ea953dcf.png

I’ve personally only seen it on Media Player for some reason. To reproduce, start an mp3, then resize the window. Now here is the really weird part. The issue doesn’t seem to occur for me if I am playing a video, only MP3. Then only if that MP3 doesn’t display artwork. Also, I’m using the Framebuffer driver on UEFI booting and VESA on an other BIOS booting system. Happens on both. Let me know if there is anything I can do to help.

**Comment by Briseur** [comment]
I noticed the glitch on a nightly simply by resizing slowly the About Haiku window.
It seems to happen only when the handle is thin, and can happen with both borders or only one of them.
I guess that the code to draw borders is the same that in Haiku others decorators (Default and Be). So I'm wondering if the reason why it doesn't happen with them is because they don't have the handle coloured.

You may want to check Track tickets for default [ControlLook](https://dev.haiku-os.org/search?q=ControlLook&noquickjump=1&ticket=on) and [Decorators](https://dev.haiku-os.org/search?q=Decorator&noquickjump=1&ticket=on) to see if something similar happens.
If unlike me you understand something to it, you can also have a look at patches proposed on Gerrit and so upcoming changes for [ControlLook](https://review.haiku-os.org/q/ControlLook) and [Decorator](https://review.haiku-os.org/q/Decorator).

**Comment by DFergFLA** [comment]
Thanks for taking a look.  I am not a developer so I only understand part of what those things are saying.  The only programming language I know at all was Pascal.  Like back in the 80's, before all this GUI stuff came about.  I'm kind of an old nerd, 53yr.  I am a software tester.  Have been for a little over 25 years now.  So,  finding bugs and logging tickets is what I do.  If you need someone to test things that you are working on.  I would be more than happy to help.  

But, I do believe you are right about the color part.   If you don't think it is an issue with your control look.  Post a ticket and see what the Haiku devs say.

Maybe you could take the Default ControlLook and put some color on the grabber and see if that does the same thing as yours.  If it does then it is a problem in Haiku and not your code.

At first look, ,these may have something to do with the issue:
[https://review.haiku-os.org/c/haiku/+/4456](url) 
[https://review.haiku-os.org/c/haiku/+/4457](url)
But I am not 100% sure.

This doesn't apply to the problem, but I did find it interesting.  
[https://review.haiku-os.org/c/haiku/+/2472](url)

**Comment by Briseur** [comment]
I'm a simple user just like you, maybe a bit more experienced with Haiku. I have no coding skills at all.
I just try to confirm bugs, to give more details and to (sometimes awkwardly) share my impressions about them.
nhtello coded these awesome ControlLook & Decorator.

**Comment by DFergFLA** [comment]
Got it.  :)

**Comment by unarix** [comment]
i cant fix it, im assuming now that is a bug in other place or a refresh problem...

**Comment by unarix** [comment]
I delete that "feature"; cose, many people have this same issue.
