### ISSUE TITLE
Switching to Flat ControlLook has no more effect

### ISSUE THREAD

**Issue by Briseur** [unarix/haiku_darkstyle#5]
Since hrev 54634, switching to Flat ControlLook seems to have no more effect.
I'm on hrev 54645 x64 with package flatstyle 0.3-1
I saw that you made some changes already so I guess that it will be fixed in next package release.;)

**Comment by unarix** [comment]
Yes! Some changes maded in haiku base code causes that flatdecor stoping work. The fix is ready and added some mods to the buttons and scrollbars look. For more info, see the pull request: #https://github.com/haikuports/haikuports/pull/5323 

As @waddlesplash says: _"Unfortunately this probably cannot be merged, because the buildbots build packages against R1/beta2, not against master"_ maybe they dont release that after B3.

I will keep this open, due haikuports guys take some desition.

**Comment by Briseur** [comment]
We are now in beta3 and the flatstyle package has finally been updated to 0.4.1.
I guess that it is safe now to close this one.

**Comment by SolsticeSpectrum** [comment]
The ControlLook doesn't work again in beta4
